version: 2
updates:
  - package-ecosystem: cargo
    directory: "."
    schedule:
      interval: daily
    # Temporarily disable Dependabot version update PRs for Cargo.
    # Re-enable this after https://github.com/youki-dev/youki/pull/3477 is merged.
    open-pull-requests-limit: 0
    allow:
      - dependency-type: direct
    groups:
      patch:
        update-types: 
        - patch
