name: 🧪 Test for podman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  podman-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Add CRIU PPA
        run: sudo add-apt-repository -y ppa:criu/ppa
      - name: Install requirements
        run: sudo env PATH=$PATH just ci-prepare

      # clone podman repository
      - name: Clone podman repository
        uses: actions/checkout@v4
        with:
          repository: containers/podman
          path: podman

      # setup lima
      - name: Setup Lima
        uses: lima-vm/lima-actions/setup@v1
        id: lima-actions-setup

      - uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: lima-${{ steps.lima-actions-setup.outputs.version }}

      - name: Start the guest VM
        run: |
          set -eux
          limactl start \
            --name=default \
            --cpus=4 \
            --memory=8 \
            --containerd=none \
            --set '.mounts=[{"location":"~/","writable":true}]' \
            template://fedora

      # setup podman dependencies
      - name: Install podman dependencies
        working-directory: podman
        run: |
          lima sudo dnf -y remove podman
          lima sudo dnf -y install catatonit conmon containers-common-extra buildah htpasswd skopeo jq bats slirp4netns nc socat
          lima sudo dnf -y builddep rpm/podman.spec

      # build youki
      - name: Build youki
        run: just youki-release

      # install youki
      - name: Install youki
        run: |
          lima sudo rm /usr/bin/crun
          lima sudo cp youki /usr/local/bin
          lima sudo cp youki /usr/bin/crun

      # build podman
      - name: Build podman
        working-directory: podman
        run: lima make SELINUXOPT="" BUILDTAGS="selinux seccomp systemd"

      # install podman
      - name: Install podman
        working-directory: podman
        run: lima sudo make install SELINUXOPT=""

      # disable selinux
      - name: Disable SELinux
        run: lima sudo setenforce 0

      # run tests
      - name: Run podman test
        working-directory: podman
        run: lima OCI_RUNTIME=/usr/local/bin/youki sudo make localsystem SELINUXOPT="" 2>&1 | tee build.log

      # add summary
      - name: Adding Summary
        working-directory: podman
        run: |
          echo "Total tests: 600+ Failed tests: $(cat build.log | grep " ok " | wc -l)" >> $GITHUB_STEP_SUMMARY
